spring:
  application:
    name: deepdive-security
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certificate.p12
    key-store-password: password

logging:
  level:
    root: INFO